### ISSUE TITLE
IR file not loaded after host restart

### ISSUE THREAD

**Issue by unfa** [HiFi-LoFi/KlangFalter#10] opened 2017-02-23 14:22 UTC
I'm hosting KlangFalter in Carla. It doesn't work after reloading the project though.
KlangFalter seems to know the sound file's name but it doesn't show the waveform, nor it produces expected audio:

![selection_281](https://cloud.githubusercontent.com/assets/491704/23262329/9db3aff6-f9da-11e6-9093-405a28b65628.png)

I had other problems with IR.lv2 plugin - it failed torecall the IR sample.
I'm not sure if it's a host- or plugin-related issue.

**What is the whole project, BTW?**

I can't hear a phone ringing on my desk, when I'm wearing headphones at work, so I'm using Carla plugin host to make my Linux machine tell me when the phone is ringing.
 
I have taped a mic to the phone, I recorded a sample of the phone ringtone and I'm using that with convolution reverb to detect when the phone rings. IR processing is essential to discriminate the phone ringtone among other sounds the mic picks up.

I was using IR.lv2 but recently it stopped recalling the IR file (https://github.com/Anchakor/ir.lv2/issues/5), so I gave KlangFalter a shot, no luck so far though.

More detail here: https://www.linuxmusicians.com/viewtopic.php?f=11&t=16638&sid=4b6df525371a990dfa9f04ba9e937653).

PS:
Possibly related IR.lv2 issue:
**https://github.com/Anchakor/ir.lv2/issues/5**

**Comment by HiFi-LoFi** [comment] 2017-03-31 22:47
Hi,

thanks for reporting.

However, I currently can't reproduce it on my machine (Mac). I also tried to reproduce it with Carla on Mac, but Carla crashed before I could load any plugin. :-( As this has been a pure hobby project of mine, I'm afraid that I can't help here for now.

Regards, Uli

**Comment by HiFi-LoFi** [comment] 2017-03-31 22:49
Seems to be a duplicate of the following issue, so I'll close it:
https://github.com/HiFi-LoFi/KlangFalter/issues/7

**Closed by HiFi-LoFi** 2017-03-31 22:49 UTC
